"""
SKELETON CODE FOR PLOTTING FIGURES 1 TO 15
------------------------------------------

This script:
1. Loads aerosol mode parameters from a CSV file generated by the C program.
2. Computes lognormal size distributions.
3. Computes approximate CCN spectra and critical supersaturations (placeholder formulas).
4. Provides placeholders for Parcel Model outputs (Nd, S_max, re, tau, albedo).
5. Plots all required figures for comparing natural vs anthropogenic aerosols.

Sections marked with TODO must be completed with real model outputs
(from Particula, Pyrcel, or other microphysical tools).

"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ---------------------------------------------------------------------
# 0. Load aerosol modes from CSV
# ---------------------------------------------------------------------

csv_file = "aerosol_modes.csv"
modes = pd.read_csv(csv_file)

print("Loaded aerosol modes:")
print(modes)

# ---------------------------------------------------------------------
# 1. Fundamental functions
# ---------------------------------------------------------------------

def lognormal_distribution(N0, Dg, sigma, D):
    """
    Computes lognormal size distribution dN/dlnD.

    Parameters:
        N0   : total number concentration (#/cm3)
        Dg   : geometric mean diameter (µm)
        sigma: geometric standard deviation
        D    : array of diameters (µm)

    Returns:
        dN/dlnD in #/cm3
    """
    return (N0 / (np.sqrt(2*np.pi) * np.log(sigma))) * \
           np.exp(- (np.log(D/Dg))**2 / (2 * (np.log(sigma))**2))


def kappa_kohler_Sc(D_dry, kappa):
    """
    Computes critical supersaturation Sc(Ddry) using a simplified κ-Köhler formulation.

    This is an approximate formula intended as a placeholder. 
    TODO: Replace with exact κ-Köhler implementation or Particula output.

    Returns:
        Sc in %
    """
    sigma_s = 0.072  # surface tension [N/m]
    R = 8.314        # J/mol/K
    T = 298
    Mw = 0.018
    rho_w = 1000

    A = 2 * sigma_s * Mw / (R * T * rho_w)
    B = 6 * kappa / rho_w

    Sc = np.sqrt((4*A**3) / (27*B*(D_dry*1e-6)**3)) * 100
    return Sc


def compute_NCCN(D, Sc_curve, S_values):
    """
    Computes an approximate CCN spectrum N_CCN(S) by counting particles 
    with Sc(D) <= S.

    TODO: Replace with proper integral over dN/dlnD using Particula.

    Returns:
        NCCN array
    """
    NCCN = []
    for S in S_values:
        activated = np.where(Sc_curve <= S)[0]
        NCCN.append(len(activated))
    return np.array(NCCN)

# ---------------------------------------------------------------------
# 2. Graph 1: dN/dlnD vs diameter for each individual aerosol mode
# ---------------------------------------------------------------------

D = np.logspace(-2, 1, 400)  # from 0.01 to 10 µm

plt.figure()
for _, row in modes.iterrows():
    dist = lognormal_distribution(row["N0_cm3"], row["Dg_um"], row["sigma_g"], D)
    plt.plot(D, dist, label=row["name"])

plt.xscale("log")
plt.yscale("log")
plt.xlabel("Dry diameter D (µm)")
plt.ylabel("dN/dlnD (#/cm³)")
plt.title("Figure 1 – Individual lognormal aerosol size distributions")
plt.legend()
plt.show()

# ---------------------------------------------------------------------
# 3. Graph 2: Total natural vs anthropogenic distributions
# ---------------------------------------------------------------------

plt.figure()
for origin in ["natural", "anthropogenic"]:
    subset = modes[modes["origin"] == origin]
    total_dist = np.zeros_like(D)
    for _, row in subset.iterrows():
        total_dist += lognormal_distribution(row["N0_cm3"], row["Dg_um"], row["sigma_g"], D)
    plt.plot(D, total_dist, label=f"{origin} total")

plt.xscale("log")
plt.yscale("log")
plt.xlabel("Dry diameter (µm)")
plt.ylabel("dN/dlnD (#/cm³)")
plt.title("Figure 2 – Total size distributions: natural vs anthropogenic")
plt.legend()
plt.show()

# ---------------------------------------------------------------------
# 4. Graph 3: κ hygroscopicity values
# ---------------------------------------------------------------------

plt.figure()
plt.bar(modes["name"], modes["kappa"])
plt.xticks(rotation=45, ha="right")
plt.ylabel("κ hygroscopicity")
plt.title("Figure 3 – κ values for each aerosol type")
plt.show()

# ---------------------------------------------------------------------
# 5. Graph 4: Total number concentration (natural vs anthropogenic)
# ---------------------------------------------------------------------

plt.figure()
nat = modes[modes["origin"] == "natural"]["N0_cm3"].sum()
ant = modes[modes["origin"] == "anthropogenic"]["N0_cm3"].sum()

plt.bar(["Natural", "Anthropogenic"], [nat, ant])
plt.ylabel("Total number concentration (#/cm³)")
plt.title("Figure 4 – Total particle number for natural vs anthropogenic aerosols")
plt.show()

# ---------------------------------------------------------------------
# 6. Graph 5: Sc(Ddry) κ-Köhler curves for each species
# ---------------------------------------------------------------------

plt.figure()
for _, row in modes.iterrows():
    Sc_curve = kappa_kohler_Sc(D, row["kappa"])
    plt.plot(D, Sc_curve, label=row["name"])

plt.xscale("log")
plt.yscale("log")
plt.xlabel("Dry diameter D (µm)")
plt.ylabel("Critical supersaturation Sc (%)")
plt.title("Figure 5 – κ-Köhler Sc(Ddry) curves")
plt.legend()
plt.show()

# ---------------------------------------------------------------------
# 7. Graph 6: CCN spectra N_CCN(S)
# ---------------------------------------------------------------------

S_values = np.logspace(-3, 0, 80)  # from 0.001% to 1%

plt.figure()
for origin in ["natural", "anthropogenic"]:
    subset = modes[modes["origin"] == origin]

    Sc_curves = []
    for _, row in subset.iterrows():
        Sc_curves.append(kappa_kohler_Sc(D, row["kappa"]))
    Sc_combined = np.min(np.array(Sc_curves), axis=0)

    NCCN = compute_NCCN(D, Sc_combined, S_values)

    plt.plot(S_values, NCCN, label=origin)

plt.xscale("log")
plt.xlabel("Supersaturation S (%)")
plt.ylabel("N_CCN (#)")
plt.title("Figure 6 – CCN spectra N_CCN(S)")
plt.legend()
plt.show()

# ---------------------------------------------------------------------
# 8. Graph 7: Activated fraction vs supersaturation
# ---------------------------------------------------------------------

plt.figure()

for origin in ["natural", "anthropogenic"]:
    subset = modes[modes["origin"] == origin]
    total_number = subset["N0_cm3"].sum()

    Sc_curves = np.array([kappa_kohler_Sc(D, row["kappa"]) 
                          for _, row in subset.iterrows()])
    Sc_combined = np.min(Sc_curves, axis=0)

    NCCN = compute_NCCN(D, Sc_combined, S_values)
    fraction = NCCN / total_number

    plt.plot(S_values, fraction, label=origin)

plt.xscale("log")
plt.xlabel("Supersaturation S (%)")
plt.ylabel("Activated fraction")
plt.title("Figure 7 – Activated aerosol fraction vs supersaturation")
plt.legend()
plt.show()

# ---------------------------------------------------------------------
# 9–15: Cloud microphysics and albedo (requires Pyrcel outputs)
# ---------------------------------------------------------------------

# Placeholder values for demonstration
# TODO: Replace with real Parcel Model results
updrafts = np.array([0.1, 0.3, 0.5, 1.0])  # m/s
Nd_nat = np.array([30, 50, 80, 120])       # placeholder values
Nd_ant = np.array([80, 120, 180, 250])

# ---------------------------------------------------------------------
# Figure 10: Nd vs total aerosol concentration
# ---------------------------------------------------------------------

plt.figure()
plt.scatter([nat], [Nd_nat[-1]], label="Natural")
plt.scatter([ant], [Nd_ant[-1]], label="Anthropogenic")
plt.xlabel("Total aerosol number (#/cm³)")
plt.ylabel("Droplet number Nd (#/cm³)")
plt.title("Figure 10 – Nd vs total aerosol concentration")
plt.legend()
plt.show()

# ---------------------------------------------------------------------
# Figure 11: Nd vs updraft
# ---------------------------------------------------------------------

plt.figure()
plt.plot(updrafts, Nd_nat, "-o", label="Natural")
plt.plot(updrafts, Nd_ant, "-o", label="Anthropogenic")
plt.xlabel("Updraft velocity w (m/s)")
plt.ylabel("Nd (#/cm³)")
plt.title("Figure 11 – Nd vs updraft velocity")
plt.legend()
plt.show()

# ---------------------------------------------------------------------
# Figure 12: Effective radius re vs Nd
# ---------------------------------------------------------------------

# TODO: replace with Pyrcel results
re_nat = (10e-3) * (50 / Nd_nat)**(1/3)
re_ant = (10e-3) * (50 / Nd_ant)**(1/3)

plt.figure()
plt.scatter(Nd_nat, re_nat, label="Natural")
plt.scatter(Nd_ant, re_ant, label="Anthropogenic")
plt.xlabel("Nd (#/cm³)")
plt.ylabel("Effective radius re (µm)")
plt.title("Figure 12 – re vs Nd")
plt.legend()
plt.show()

# ---------------------------------------------------------------------
# Figure 13: Optical depth τ vs Nd
# ---------------------------------------------------------------------

# Placeholder formula: tau = 30 / re
# TODO: Replace with real microphysical calculation
tau_nat = 30 / re_nat
tau_ant = 30 / re_ant

plt.figure()
plt.scatter(Nd_nat, tau_nat, label="Natural")
plt.scatter(Nd_ant, tau_ant, label="Anthropogenic")
plt.xlabel("Nd (#/cm³)")
plt.ylabel("Optical depth τ")
plt.title("Figure 13 – τ vs Nd")
plt.legend()
plt.show()

# ---------------------------------------------------------------------
# Figure 14: Albedo vs Nd
# ---------------------------------------------------------------------

# Approximation: R = tau / (tau + 7.7)
R_nat = tau_nat / (tau_nat + 7.7)
R_ant = tau_ant / (tau_ant + 7.7)

plt.figure()
plt.scatter(Nd_nat, R_nat, label="Natural")
plt.scatter(Nd_ant, R_ant, label="Anthropogenic")
plt.xlabel("Nd (#/cm³)")
plt.ylabel("Cloud albedo")
plt.title("Figure 14 – Albedo vs Nd")
plt.legend()
plt.show()

# ---------------------------------------------------------------------
# Figure 15: ΔR vs updraft
# ---------------------------------------------------------------------

delta_R = R_ant - R_nat

plt.figure()
plt.plot(updrafts, delta_R, "-o")
plt.xlabel("Updraft velocity w (m/s)")
plt.ylabel("ΔR = R_anthro − R_nat")
plt.title("Figure 15 – Change in albedo ΔR as a function of updraft")
plt.show()
